allowBuilds:
  '@google/genai': true
  core-js: false
  protobufjs: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.110.5'
  - '@supabase/functions-js@2.110.5'
  - '@supabase/postgrest-js@2.110.5'
  - '@supabase/realtime-js@2.110.5'
  - '@supabase/ssr@0.12.3'
  - '@supabase/storage-js@2.110.5'
  - '@supabase/supabase-js@2.110.5'
